### ISSUE TITLE
xip binary not found?

### ISSUE THREAD

**Issue by aRUNTU** [OfficialTeamUIX/UIX-Lite-Xips#3]
Hello, first of all thanks for your work. I do not have experience with github, so sorry if this is not a chat or whatever, truly sorry. I have landed here as I cannot find info about this or tutorials, I know you are very busy people, sorry again.

The thing is I do not have a file explorer in UIX ultra little so I found an image (jpeg) of a file explorer pointing to team uix, 

I found that 8 months ago, here, there are at least 3 files indicating "file explorer" changes, so I tried to install the patches on my ultra lite dashboard

Interestingly the sources folder is already on the xboxdashdata.185ead00 folder; I try to run the xip batch anywhere on my windows 10 pc, no luck  

"Tools\xip-binary\xip' n’est pas reconnu en tant que commande interne
ou externe, un programme exécutable ou un fichier de commandes." french message saying that no xip xommand found; 

The only content of the binary files tools si the cmd files, no xip.exe found

What I am missing guys, will I have a file explorer for UIX dashboard some day? 

THANKS!!!!

**Comment by nononymousse** [comment]
there is currently 2 UIX projects that are been worked on :
- UIX Lite, based on a older dash and is heavily modified (skins, FTP server, ect)
- UIX Ultra LIte, based on the latest dash, compatible with Insignia (they didn’t removed the XBL stuff)

currently UIX Lite is on pause but that might be the dash you have seen that has a file explorer. Ultra Lite doesn’t currently have one and it’s not planned (doesn’t mean it won’t happen tho)

also you are currently on the UIX Lite repo, you can go on the Ultra Lite one here https://github.com/MrMilenko/UIX-Ultra-Lite

and XIP’s are Xbox Dashboard files and are not executable and cannot run on a PC

**Comment by aRUNTU** [comment]
1. Thank you very much! I was very confused, so, If I want all the UIX Lite goods I should download the UIX Lite v1.0.5b sources and patch my vanilla xboxdashdata.185ead00 with them, by using the uix-lite-xips tools, which , by the way, are developed by ... MrMilenko too!!!, OK, weird, but OK,  (prepatched xboxdashdata.185ead00 for UIX lite does not exist apparently on github?).

1. On the Batch File Readme.txt
 we have:

"When you run either batch it looks for ..\xip-binary\xip.exe"

and also

"
-xip-binary (folder)
--xip.exe
"

That 2 lines make me thing that it must to exist a xip.exe file, wich I cannot find on the **[xip binary folder](https://github.com/OfficialTeamUIX/UIX-Lite-Xips/tree/main/Tools/xip-binary)**

Is that expected???

and finally

2. I got to find the uix little (not ultra lite) in an ISO I found on the wild, but I cannot check its version (no version txt at all) and it crashes if I put my games path G:/Games and after that I launch the Games option. Maybe if I exchange manually the  xap files  (I can open them from the xbox file explorer) with those which are inside the folders labeled as UIX Lite v1.0.5b standard folder source, would my Games work? I can do it to test it but I do not know if I'm going to break something else anyway.


My situation:  red pill:    If I chose UIX ultralite no file explorer
                       blue pill:  If I chose UIX little Games crash

Thank you, never thought that the learning curve was going to be so high

**Comment by nononymousse** [comment]
1- if by sources you mean this repo, it’s not that. that repo is the sources of the Xips who are complementary to the executable and other files available elsewhere (for legal reasons). UIX Lite is pretty buggy tbh and you can test it if you want but personally UIX Ultra Lite is way more usable, even tho it has less features for now but that can be combined with other dash who has the functions you need (i have entries in UIX Ultra Lite to launch other dashs when i need to FTP something or browse files).

also UIX Lite can be installed in any partition of a Xbox but Ultra Lite has to be at the same place than the 5960 Dash (the latest one) and files should not be mixed between the two (since UIX Lite is a modified 4920 Dash).

> by the way, are developed by ... MrMilenko too!!!, OK, weird, but OK

Milenko was part of TeamUIX but the team is now defunct if i understood currently and he try to still work on UIX dashes.

> EDIT: What are "common places"? I'm old, is it IRC? Arpanet? BBM?

for legal/GitHub ToS i don’t think i can tell you 😅 (that’s why UIX Ultra Lite exist too, to go back on a fresh state and providing patches, not final binaries and Xips that are copyrighted material)

2- i can’t help you at all on UIX Lite, i only tried it but never messed with the XIP’s

3- same, can’t help you on this 😅

**Comment by aRUNTU** [comment]
Thank you very much, I feel like I'm 15 (or more) years late to the party, but however, it is weird that the last commit date is about 8 months old, I havent talked to my accountant for more than that... but I believe you 100%, so sad that so much love and effort has been put on this work but things must go on I suppose. Thanks again.
